<?php

/**
 * Implements hook_field_formatter_info().
 */
function resistoflex_formatters_field_formatter_info() {
  return array(
    'bqsliderpro_formatter' => array( //Machine name of the formatter
      'label' => t('BQ Slider'),
      'field types' => array('image'),
      'settings'  => array(),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function resistoflex_formatters_field_formatter_settings_summary($field, $instance, $view_mode) {
  $summary = t('Format images for bqslider'); // we use t() for translation and placeholders to guard against attacks
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function resistoflex_formatters_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array(); // Initialize the var
  $markup = "";
  $thumbnails = "";

  foreach ($items as $delta => $item) {
    $image  = '<div class="sp-slide">';
      $image .= '<img class="sp-image" src="' . base_path() . 'sites/default/files/' . $item['filename'] . '" alt="' . t($item['alt']) . '" title="' . t($item['title']) . '" />';

      $title = trim($item['title']);
      if($title) {
        $image .= '<p class="sp-layer sp-black sp-padding" data-show-delay="500" data-show-transition="left" data-width="35%" data-horizontal="20" data-vertical="20">' . $title . '</p>';
      }      
    $image .= '</div>';

    // Assign image to markup
    $markup .= $image;

    $thumbnail =  '<div class="sp-thumbnail">';
      $thumbnail .= '<img class="sp-thumbnail-image" src="' . base_path() . 'sites/default/files/' . $item['filename'] . '" />';
    $thumbnail .= '</div>';

    $thumbnails .= $thumbnail;
  }

  $slides = '<div class="sp-slides">' . $markup  . '</div>';
  $thumbnails = '<div class="sp-thumbnails" data-width="100%">' . $thumbnails . '</div>';

  $element[0]['#markup']  = '<div class="slider-pro" id="my-slider">';
    $element[0]['#markup'] .= $slides;
    $element[0]['#markup'] .= $thumbnails;
  $element[0]['#markup'] .= '</div>';
  return $element;
}