<?php

$plugin = array(
  'title' => t('Project Layout'),
  'icon' => 'project-layout.png',
  'category' => t('Resistoflex'),
  'theme' => 'project-layout',
  'regions' => array(
    'title' => t('Title'),
    'code' => t('Code'),
    'description' => t('Description'),
    'client' => t('Client'),
    'location' => t('Location'),
    'photo' => t('Photo'),
    'used_products' => t('Used Products'),
    'availed_services' => t('Availed Services'),
    'is_featured' => t('Is Featured'),
  ),
);
